### ISSUE TITLE
Warn before exit Message

### ISSUE THREAD

**Issue by martindsouza** [grlicaa/AutoNumeric#3]
Example: If changing a number to a percentage (`0.12` to `12%`) everything displays properly on the screen for the user. If the user tries to exit page without saving (ie `cancel` etc) they'll get the warning before saving.

Need to resolve this issue so that this is not raised. Sample snippet to resolve:

```javascript
elem.setAttribute('value', apex.item(elem).getValue());
```

**Comment by martindsouza** [comment]
Full solution (in JS file):

```javascript
...

isChanged:function() {
      // #3: Use the unformated numer to determine if the value has been changed or not
			return (this.node.defaultValue != (AutoNumeric.isManagedByAutoNumeric("#"+this.id) ? AutoNumeric.getNumber("#"+this.id) : this.getValue()));
		},

```

**Comment by grlicaa** [comment]
Nice one seems more neat and clean, I'll change with current setting : 
```javascript
		isChanged:function() {
			return (this.node.defaultValue != this.getValue());
		},
```

**Comment by martindsouza** [comment]
@grlicaa I'm actually working on all the changes so give me the day before you apply. I'll do a PR and you can apply the changes you want

**Comment by grlicaa** [comment]
@martindsouza  Perfect :)
Thank you, any help is much appreciated.

**Comment by grlicaa** [comment]
Added to version 4.6.0.4
