### ISSUE TITLE
Document the ability to use variables instead of hard coding same option each time

### ISSUE THREAD

**Issue by martindsouza** [grlicaa/AutoNumeric#5]
For the AutoNumeric Options we don't need to constantly copy the JSON object for each page item. 

Instead you can define a global JS variable and reference it.

**Comment by grlicaa** [comment]
I'll merge it during next week. If something else pop's up, please let me know.
Thank you for your effort :)

**Comment by martindsouza** [comment]
@grlicaa perfect. Please read the PR notes in #6 as I think some manual steps will be required to merge. Shouldn't be too hard though.

**Comment by grlicaa** [comment]
Added to Item help, documentation and sample in demo application. Thank you for suggestion.
Added to version 4.6.0.4
