### ISSUE TITLE
Interactive Grid column aggregation

### ISSUE THREAD

**Issue by jariolaine** [grlicaa/AutoNumeric#8]
When using plugin in Interactive Grid, aggregation for numbers not working as expected.
Fix for that is described on APEX forum post [Interactive Grid column aggregation when column type is plugin
](https://forums.oracle.com/ords/apexds/post/interactive-grid-column-aggregation-when-column-type-is-plu-5225).

Could you please implement this fix to plugin?

**Comment by grlicaa** [comment]
Hi @jariolaine,

Thank you for reporting this. The request is reasonable and needed so I will include that this week in a new release, 
This plug-in was moved inside "United Codes" [https://github.com/plug-ins-pro/auto_numeric](https://github.com/plug-ins-pro/auto_numeric)
as a free plug-in, to assure developers it will still be supported, updated, and fixed if needed.

When I update it to a new version I'll also post it here, and change the readme to link the plugin to a new location.

Once again thank you!

Kind regards,
Andrej Grlica

**Comment by jariolaine** [comment]
Hi Andrej,

Thank you very much!
And thank you for sharing this great plugin.

Regards,
Jari

**Comment by grlicaa** [comment]
Fixed and released under UnitedCodes.
https://github.com/plug-ins-pro/auto_numeric/releases

Kind regards;
Andrej
